### ISSUE TITLE
Unknown method invocation  'file' on WorkflowHicer type

### ISSUE THREAD

**Issue by MarinaMakh** [PavriLab/hicer-nf#5]
Hey!
I get this error when running hicer-nf on cluster:
`ERROR ~ Unknown method invocation  'file' on WorkflowHicer type
 -- Check script '/home/makharov/.nextflow/assets/pavrilab/hicer-nf/./workflows/hicer.nf' at line: 95 or see '.nextflow.log' file for more details`

Command used:
`nextflow run pavrilab/hicer-nf -profile singularity --input /mydir/samples.txt --igenomes_ignore T --fasta /mydir/GCF_000001635.27_GRCm39_genomic.fna --chromSizes /mydir/chromSizes.tsv --re ^GATC,MboI`

Could you please help?

**Comment by dmalzl** [comment]
Hey sorry for the late reply,

Would you mind to tell me which nextflow version you are using?

**Comment by MarinaMakh** [comment]
Nextflow version 23.10.1
[nextflow.log.txt](https://github.com/PavriLab/hicer-nf/files/14283426/nextflow.log.txt)

**Comment by dmalzl** [comment]
Thank you very much.

It should be fixed now. The problem was an incorrect invocation of the `file` method in Groovy, which never occurred in our case since we always tested with XML files.

Will close now. but feel free to reopen if there's still a problem with it.

Please also make sure that there is no empty line and no header in the chromsize file.
